In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# read in all the words
words = open('/content/drive/MyDrive/GitHub/makemore_names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [3]:
len(words)

32033

In [4]:
# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s: i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [5]:
# build the dataset

block_size = 3 # context length: how many characters do we take to predict the next one?
X, Y = [], []
for w in words[:5]:

  print(w)
  context = [0] * block_size
  for ch in w + '.':
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    print(''.join(itos[i] for i in context), '--->', itos[ix])
    context = context[1:] + [ix] # crop and append

X = torch.tensor(X)
Y = torch.tensor(Y)

emma
... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
olivia
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .
ava
... ---> a
..a ---> v
.av ---> a
ava ---> .
isabella
... ---> i
..i ---> s
.is ---> a
isa ---> b
sab ---> e
abe ---> l
bel ---> l
ell ---> a
lla ---> .
sophia
... ---> s
..s ---> o
.so ---> p
sop ---> h
oph ---> i
phi ---> a
hia ---> .


In [6]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([32, 3]), torch.int64, torch.Size([32]), torch.int64)

In [7]:
C = torch.randn((27, 2))

In [8]:
C[5]

tensor([-1.1611,  0.8741])

In [9]:
F.one_hot(torch.tensor(5), num_classes=27).float() @ C

tensor([-1.1611,  0.8741])

In [12]:
C[X].shape

torch.Size([32, 3, 2])

In [13]:
X[13, 2]

tensor(1)

In [15]:
C[X][13, 2]

tensor([1.1809, 0.5740])

In [16]:
C[1]

tensor([1.1809, 0.5740])

In [19]:
emb = C[X]
emb.shape

torch.Size([32, 3, 2])

In [61]:
W1 = torch.randn((6, 100))
b1 = torch.randn(100)

In [70]:
h = torch.tanh(emb.view(-1, 6) @ W1 + b1)

In [71]:
h

tensor([[-0.3881, -0.9121,  0.8155,  ...,  0.9927,  0.4665, -0.9823],
        [-0.2717,  0.9950,  0.3897,  ...,  0.9018,  0.6595, -0.9965],
        [ 0.8039,  0.1409, -0.9978,  ..., -0.9703, -0.9844,  0.7847],
        ...,
        [ 0.2249,  0.9897,  0.6700,  ...,  0.9950,  0.7714, -0.9973],
        [-0.4982, -0.6724, -0.9398,  ...,  0.8639, -0.9591, -0.6304],
        [ 0.8081,  0.9748, -0.8535,  ...,  0.9072,  0.5226, -0.6761]])

In [72]:
h.shape

torch.Size([32, 100])